[workspace]
authors = ["codewithprags <pragati.dwivedi@outlook.com>"]
channels = ["conda-forge"]
name = "MlP-Capstone"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
numpy = ">=2.3.1,<3"
pandas = ">=2.3.1,<3"
ucimlrepo = ">=0.0.7,<0.0.8"
scikit-learn = ">=1.7.0,<2"
jupyter = ">=1.1.1,<2"
